#!/usr/bin/env node
/**
 * Nexus CLI — configure by commands (no need to hand-edit files).
 * Local files written here stay gitignored.
 */
import {
  createInterface,
  type Interface,
} from "node:readline";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { spawn } from "node:child_process";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "../../..");
const [cmd, sub, ...rest] = process.argv.slice(2);
const isWin = process.platform === "win32";

function help() {
  console.log(`Fengyun Nexus 指令（主中文）

启动：
  nexus boot              一键启动（电脑会开网关+界面；Termux 默认精简只开网关）
  nexus boot lite         只开网关（手机/服务器省资源，浏览器打开网关地址）
  nexus boot full         网关 + Web 开发界面

环境姿态（不用改文件）：
  nexus env               查看当前
  nexus env desktop|mobile|server|termux

交互配置（写入本地，不上传）：
  nexus setup             设置管理用户名/密码
  nexus set llm-key <值>
  nexus set llm-url <值>
  nexus set llm-model <值>
  nexus set registry-token <值>
  nexus status            查看配置摘要（密钥打码）

其它：
  nexus create plugin <名>
  nexus registry show
  nexus help
`);
}

function ask(rl: Interface, q: string, def = ""): Promise<string> {
  const tip = def ? `${q}（默认 ${def}）: ` : `${q}: `;
  return new Promise((resolveAsk) => {
    rl.question(tip, (ans) => resolveAsk((ans || def).trim()));
  });
}

function readJson<T>(p: string, fallback: T): T {
  if (!existsSync(p)) return fallback;
  try {
    return JSON.parse(readFileSync(p, "utf8")) as T;
  } catch {
    return fallback;
  }
}

function writeJson(p: string, data: unknown): void {
  mkdirSync(dirname(p), { recursive: true });
  writeFileSync(p, `${JSON.stringify(data, null, 2)}\n`, "utf8");
}

function readEnvFile(): Record<string, string> {
  const out: Record<string, string> = {};
  const p = join(root, ".env");
  if (!existsSync(p)) return out;
  for (const line of readFileSync(p, "utf8").split(/\r?\n/)) {
    const t = line.trim();
    if (!t || t.startsWith("#")) continue;
    const i = t.indexOf("=");
    if (i <= 0) continue;
    out[t.slice(0, i).trim()] = t.slice(i + 1).trim();
  }
  return out;
}

function writeEnvFile(map: Record<string, string>): void {
  const lines = [
    "# Generated by: nexus set / nexus setup — local only, not uploaded",
    ...Object.entries(map).map(([k, v]) => `${k}=${v}`),
    "",
  ];
  writeFileSync(join(root, ".env"), lines.join("\n"), "utf8");
}

function mask(v?: string): string {
  if (!v) return "(未设置)";
  if (v.length <= 4) return "****";
  return `${v.slice(0, 2)}***${v.slice(-2)}`;
}

function isTermux(): boolean {
  return Boolean(
    process.env.TERMUX_VERSION ||
      process.env.PREFIX?.includes("com.termux") ||
      process.env.NEXUS_FORCE_TERMUX === "1",
  );
}

function currentEnv(): string {
  const runtime = readJson<{ env?: string }>(join(root, "configs/runtime.local.json"), {});
  return process.env.NEXUS_ENV || runtime.env || (isTermux() ? "termux" : "desktop");
}

function setEnv(id: string): void {
  const ok = ["desktop", "mobile", "server", "termux"];
  if (!ok.includes(id)) {
    console.error("可用：desktop | mobile | server | termux");
    process.exit(1);
  }
  writeJson(join(root, "configs/runtime.local.json"), { env: id, updatedAt: new Date().toISOString() });
  const envMap = readEnvFile();
  envMap.NEXUS_ENV = id;
  writeEnvFile(envMap);
  console.log(`已切换环境姿态 → ${id}（已写入本地配置，不会上传）`);
  console.log("下次 nexus boot 生效。");
}

async function setupInteractive(): Promise<void> {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  try {
    console.log("管理账号设置（只写本机 configs/admin.local.json，不上传）");
    const username = await ask(rl, "新用户名", "owner");
    const password = await ask(rl, "新密码（至少 8 位）");
    const confirm = await ask(rl, "再输入一次密码");
    if (username.length < 3) throw new Error("用户名至少 3 位");
    if (password.length < 8) throw new Error("密码至少 8 位");
    if (password !== confirm) throw new Error("两次密码不一致");
    if (username === "console" && password === "console") {
      throw new Error("请勿继续使用初始 console/console");
    }
    writeJson(join(root, "configs/admin.local.json"), {
      username,
      passwordEnv: "NEXUS_ADMIN_PASSWORD",
      defaultPassword: password,
      sessionHours: 12,
      setupCompleted: true,
    });
    console.log("已保存。请 nexus boot 后用新账号登录（旧登录态会失效）。");
  } finally {
    rl.close();
  }
}

function setKey(kind: string, value: string): void {
  if (!value) {
    console.error("缺少值。例：nexus set llm-key sk-xxx");
    process.exit(1);
  }
  const map = readEnvFile();
  const table: Record<string, string> = {
    "llm-key": "NEXUS_LLM_API_KEY",
    "llm-url": "NEXUS_LLM_BASE_URL",
    "llm-model": "NEXUS_LLM_MODEL",
    "registry-token": "NEXUS_REGISTRY_TOKEN",
  };
  const envKey = table[kind];
  if (!envKey) {
    console.error("支持：llm-key | llm-url | llm-model | registry-token");
    process.exit(1);
  }
  map[envKey] = value;
  writeEnvFile(map);
  console.log(`已写入本地 .env → ${envKey}=${mask(value)}（不上传）`);
}

function status(): void {
  const admin = readJson<{ username?: string; setupCompleted?: boolean }>(
    join(root, "configs/admin.local.json"),
    {},
  );
  const envMap = readEnvFile();
  console.log(`环境姿态: ${currentEnv()}`);
  console.log(`Termux 检测: ${isTermux() ? "是" : "否"}`);
  console.log(`管理用户: ${admin.username || "console（初始）"}`);
  console.log(`已完成首次改密: ${admin.setupCompleted ? "是" : "否"}`);
  console.log(`LLM Key: ${mask(envMap.NEXUS_LLM_API_KEY)}`);
  console.log(`Registry Token: ${mask(envMap.NEXUS_REGISTRY_TOKEN)}`);
  console.log("本地文件不会上传：.env、configs/*.local.json");
}

function createPlugin(name: string) {
  const id = name.trim() || "my-plugin";
  const dir = resolve(root, "plugins", "local", id);
  if (existsSync(dir)) {
    console.error("exists:", dir);
    process.exit(1);
  }
  mkdirSync(join(dir, "src"), { recursive: true });
  writeJson(join(dir, "nexus.plugin.json"), {
    id: `local.${id}`,
    name: id,
    version: "0.1.0",
    main: "src/index.ts",
    hooks: ["onMessage", "onReady"],
    permissions: ["channel.send"],
    category: "local",
  });
  writeFileSync(
    join(dir, "src/index.ts"),
    `import { definePlugin } from "@fengyun/nexus-plugin-sdk";
import { newId, nowIso } from "@fengyun/nexus-shared";

export default definePlugin({
  manifest: {
    id: "local.${id}",
    name: "${id}",
    version: "0.1.0",
    hooks: ["onMessage"],
    permissions: ["channel.send"],
    category: "local",
  },
  onMessage(msg) {
    if (!msg.content.startsWith("/${id} ")) return null;
    return {
      id: newId("msg"),
      channel: msg.channel,
      chatId: msg.chatId,
      userId: "plugin:${id}",
      type: "text",
      content: msg.content.slice(${id.length + 2}),
      meta: { replyTo: msg.id },
      createdAt: nowIso(),
    };
  },
});
`,
  );
  console.log("created", dir);
}

function boot(mode?: string): void {
  const args = ["boot"];
  if (mode === "lite" || mode === "full") {
    process.env.NEXUS_BOOT_MODE = mode;
  }
  const child = spawn(isWin ? "pnpm.cmd" : "pnpm", args, {
    cwd: root,
    stdio: "inherit",
    shell: isWin,
    env: process.env,
  });
  child.on("exit", (code) => process.exit(code ?? 0));
}

async function main() {
  if (!cmd || cmd === "help" || cmd === "-h") {
    help();
    return;
  }
  if (cmd === "boot") {
    boot(sub);
    return;
  }
  if (cmd === "env") {
    if (!sub) {
      console.log(currentEnv());
      return;
    }
    setEnv(sub);
    return;
  }
  if (cmd === "setup") {
    await setupInteractive();
    return;
  }
  if (cmd === "set") {
    setKey(sub, rest.join(" ").trim());
    return;
  }
  if (cmd === "status") {
    status();
    return;
  }
  if (cmd === "create" && sub === "plugin") {
    createPlugin(rest[0] ?? "my-plugin");
    return;
  }
  if (cmd === "registry" && sub === "show") {
    const local = join(root, "configs/registry.local.json");
    const def = join(root, "configs/registry.json");
    console.log(readFileSync(existsSync(local) ? local : def, "utf8"));
    return;
  }
  help();
  process.exit(1);
}

main().catch((e) => {
  console.error(e instanceof Error ? e.message : e);
  process.exit(1);
});
