#!/usr/bin/env node
/**
 * Nexus CLI — 配置 / PM2 启停 / 启动台入口
 */
import { createInterface, type Interface } from "node:readline";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { spawn, spawnSync, execSync } from "node:child_process";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "../../..");
const rawArgs = process.argv.slice(2).filter((a) => a !== "--");
const [cmd, sub, ...rest] = rawArgs;
const isWin = process.platform === "win32";

function help() {
  console.log(`Fengyun Nexus

  nexus start              PM2 后台启动框架
  nexus stop               停止框架
  nexus restart            重启框架
  nexus logs [-f] [行数]   框架日志（-f 跟随）
  nexus desk [QQ] [端口]   启动台：填 QQ/端口 → 配好 → 启 NapCat → 跟日志
  nexus nc start|stop|logs|status
  nexus boot               前台启动（调试）
  nexus setup              首次改密
  nexus env [姿态]
  nexus status
  nexus help

  一键安装后默认 PM2 后台；看日志：nexus logs -f
`);
}

function ask(rl: Interface, q: string, def = ""): Promise<string> {
  const tip = def ? `${q}（默认 ${def}）: ` : `${q}: `;
  return new Promise((resolveAsk) => {
    rl.question(tip, (ans) => resolveAsk((ans || def).trim()));
  });
}

function readJson<T>(p: string, fallback: T): T {
  if (!existsSync(p)) return fallback;
  try {
    return JSON.parse(readFileSync(p, "utf8")) as T;
  } catch {
    return fallback;
  }
}

function writeJson(p: string, data: unknown): void {
  mkdirSync(dirname(p), { recursive: true });
  writeFileSync(p, `${JSON.stringify(data, null, 2)}\n`, "utf8");
}

function readEnvFile(): Record<string, string> {
  const out: Record<string, string> = {};
  const p = join(root, ".env");
  if (!existsSync(p)) return out;
  for (const line of readFileSync(p, "utf8").split(/\r?\n/)) {
    const t = line.trim();
    if (!t || t.startsWith("#")) continue;
    const i = t.indexOf("=");
    if (i <= 0) continue;
    out[t.slice(0, i).trim()] = t.slice(i + 1).trim();
  }
  return out;
}

function writeEnvFile(map: Record<string, string>): void {
  const lines = [
    "# Generated by: nexus set / nexus setup — local only, not uploaded",
    ...Object.entries(map).map(([k, v]) => `${k}=${v}`),
    "",
  ];
  writeFileSync(join(root, ".env"), lines.join("\n"), "utf8");
}

function mask(v?: string): string {
  if (!v) return "(未设置)";
  if (v.length <= 4) return "****";
  return `${v.slice(0, 2)}***${v.slice(-2)}`;
}

function isTermux(): boolean {
  return Boolean(
    process.env.TERMUX_VERSION ||
      process.env.PREFIX?.includes("com.termux") ||
      process.env.NEXUS_FORCE_TERMUX === "1",
  );
}

function currentEnv(): string {
  const runtime = readJson<{ env?: string }>(join(root, "configs/runtime.local.json"), {});
  return process.env.NEXUS_ENV || runtime.env || (isTermux() ? "termux" : "desktop");
}

function setEnv(id: string): void {
  const ok = ["desktop", "mobile", "server", "termux"];
  if (!ok.includes(id)) {
    console.error("可用：desktop | mobile | server | termux");
    process.exit(1);
  }
  writeJson(join(root, "configs/runtime.local.json"), {
    env: id,
    updatedAt: new Date().toISOString(),
  });
  const envMap = readEnvFile();
  envMap.NEXUS_ENV = id;
  writeEnvFile(envMap);
  console.log(`已切换环境姿态 → ${id}`);
}

function runNodeScript(scriptRel: string, args: string[]): number {
  const script = join(root, scriptRel);
  const r = spawnSync(process.execPath, [script, ...args], {
    cwd: root,
    stdio: "inherit",
    env: process.env,
  });
  return r.status ?? 1;
}

function runOps(args: string[]): number {
  const r = spawnSync(
    isWin ? "pnpm.cmd" : "pnpm",
    ["exec", "tsx", join(root, "scripts/nexus-ops.ts"), ...args],
    { cwd: root, stdio: "inherit", shell: isWin, env: process.env },
  );
  return r.status ?? 1;
}

function hasPm2(): boolean {
  try {
    execSync(isWin ? "where pm2" : "command -v pm2", { stdio: "ignore" });
    return true;
  } catch {
    return false;
  }
}

function ensurePm2OrTip(): boolean {
  if (hasPm2()) return true;
  console.log(">>> 未检测到 PM2，正在安装…");
  const code = runNodeScript("scripts/ensure-runtime.mjs", ["--pm2-only"]);
  return code === 0 && hasPm2();
}

async function setupInteractive(): Promise<void> {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  try {
    console.log("管理账号设置（只写本机，不上传）");
    console.log("用户名：4–8 位英文字母；密码：至少 4 位，须含大小写、数字、特殊字符");
    const username = await ask(rl, "新用户名", "owner");
    const password = await ask(rl, "新密码");
    const confirm = await ask(rl, "再输入一次密码");
    if (!/^[A-Za-z]{4,8}$/.test(username)) throw new Error("用户名须为 4–8 位英文字母");
    if (username.toLowerCase() === "console") throw new Error("请勿使用保留名 console");
    if (password.length < 4) throw new Error("密码至少 4 位");
    const missing = [];
    if (!/[a-z]/.test(password)) missing.push("小写字母");
    if (!/[A-Z]/.test(password)) missing.push("大写字母");
    if (!/[0-9]/.test(password)) missing.push("数字");
    if (!/[^A-Za-z0-9]/.test(password)) missing.push("特殊字符");
    if (missing.length) throw new Error(`密码复杂度不足，还缺：${missing.join("、")}`);
    if (password !== confirm) throw new Error("两次密码不一致");
    writeJson(join(root, "configs/admin.local.json"), {
      username,
      passwordEnv: "NEXUS_ADMIN_PASSWORD",
      defaultPassword: password,
      sessionHours: 12,
      setupCompleted: true,
    });
    console.log("已保存。请 nexus start 后用新账号登录。");
  } finally {
    rl.close();
  }
}

function setKey(kind: string, value: string): void {
  if (!value) {
    console.error("缺少值。例：nexus set llm-key sk-xxx");
    process.exit(1);
  }
  const map = readEnvFile();
  const table: Record<string, string> = {
    "llm-key": "NEXUS_LLM_API_KEY",
    "llm-url": "NEXUS_LLM_BASE_URL",
    "llm-model": "NEXUS_LLM_MODEL",
    "registry-token": "NEXUS_REGISTRY_TOKEN",
  };
  const envKey = table[kind];
  if (!envKey) {
    console.error("支持：llm-key | llm-url | llm-model | registry-token");
    process.exit(1);
  }
  map[envKey] = value;
  writeEnvFile(map);
  console.log(`已写入本地 .env → ${envKey}=${mask(value)}`);
}

function frameworkPm2Line(): string {
  try {
    const raw = execSync("pm2 jlist", { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] });
    const list = JSON.parse(raw || "[]") as Array<{
      name?: string;
      pid?: number;
      pm2_env?: { status?: string };
    }>;
    const hit = list.find((p) => p.name === "nexus");
    if (!hit) return "框架 PM2: nexus · stopped";
    return `框架 PM2: nexus · ${hit.pm2_env?.status || "?"}${hit.pid ? ` · pid ${hit.pid}` : ""}`;
  } catch {
    return hasPm2() ? "框架 PM2: 无法读取" : "框架 PM2: 未安装";
  }
}

function status(): void {
  const admin = readJson<{ username?: string; setupCompleted?: boolean }>(
    join(root, "configs/admin.local.json"),
    {},
  );
  const envMap = readEnvFile();
  const onebot = readJson<{
    enabled?: boolean;
    bots?: Array<{ selfId?: string }>;
  }>(join(root, "configs/onebot.local.json"), {});
  const markerPath = join(root, "data/runtimes/napcat/installed.json");
  const marker = readJson<{ home?: string; flavor?: string }>(markerPath, {});
  console.log(`环境姿态: ${currentEnv()}`);
  console.log(`Termux 检测: ${isTermux() ? "是" : "否"}`);
  console.log(frameworkPm2Line());
  console.log(
    `NapCat 安装: ${marker.home || join(root, "data/runtimes/napcat")}${marker.flavor ? `（${marker.flavor}）` : ""}`,
  );
  console.log(
    `OneBot: ${onebot.enabled === false ? "关" : "开"} · 号 ${onebot.bots?.filter((b) => b.selfId).length || 0}`,
  );
  console.log(`管理用户: ${admin.username || "console（初始）"}`);
  console.log(`已完成首次改密: ${admin.setupCompleted ? "是" : "否"}`);
  console.log(`LLM Key: ${mask(envMap.NEXUS_LLM_API_KEY)}`);
  if (hasPm2()) {
    try {
      runOps(["nc", "status"]);
    } catch {
      /* ignore */
    }
  }
}

function createPlugin(name: string) {
  const id = name.trim() || "my-plugin";
  const dir = resolve(root, "plugins", "local", id);
  if (existsSync(dir)) {
    console.error("exists:", dir);
    process.exit(1);
  }
  mkdirSync(join(dir, "src"), { recursive: true });
  writeJson(join(dir, "nexus.plugin.json"), {
    id: `local.${id}`,
    name: id,
    version: "0.1.0",
    main: "src/index.ts",
    hooks: ["onMessage", "onReady"],
    permissions: ["channel.send"],
    category: "local",
  });
  writeFileSync(
    join(dir, "src/index.ts"),
    `import { definePlugin } from "@fengyun/nexus-plugin-sdk";
import { newId, nowIso } from "@fengyun/nexus-shared";

export default definePlugin({
  manifest: {
    id: "local.${id}",
    name: "${id}",
    version: "0.1.0",
    hooks: ["onMessage"],
    permissions: ["channel.send"],
    category: "local",
  },
  onMessage(msg) {
    if (!msg.content.startsWith("/${id} ")) return null;
    return {
      id: newId("msg"),
      channel: msg.channel,
      chatId: msg.chatId,
      userId: "plugin:${id}",
      type: "text",
      content: msg.content.slice(${id.length + 2}),
      meta: { replyTo: msg.id },
      createdAt: nowIso(),
    };
  },
});
`,
  );
  console.log("created", dir);
}

function bootForeground(mode?: string): void {
  if (mode === "lite" || mode === "full") {
    process.env.NEXUS_BOOT_MODE = mode;
  }
  process.env.NEXUS_FOREGROUND = "1";
  const child = spawn(isWin ? "pnpm.cmd" : "pnpm", ["boot"], {
    cwd: root,
    stdio: "inherit",
    shell: isWin,
    env: process.env,
  });
  child.on("exit", (code) => process.exit(code ?? 0));
}

async function main() {
  if (!cmd || cmd === "help" || cmd === "-h") {
    help();
    return;
  }
  if (cmd === "start") {
    if (!ensurePm2OrTip()) process.exit(1);
    process.exit(runNodeScript("scripts/pm2-nexus.mjs", ["start"]));
  }
  if (cmd === "stop") {
    process.exit(runNodeScript("scripts/pm2-nexus.mjs", ["stop"]));
  }
  if (cmd === "restart") {
    if (!ensurePm2OrTip()) process.exit(1);
    process.exit(runNodeScript("scripts/pm2-nexus.mjs", ["restart"]));
  }
  if (cmd === "logs") {
    const args = [sub, ...rest].filter(Boolean);
    process.exit(runNodeScript("scripts/pm2-nexus.mjs", ["logs", ...args]));
  }
  if (cmd === "desk") {
    process.exit(runOps(["desk", sub, ...rest].filter(Boolean)));
  }
  if (cmd === "nc") {
    process.exit(runOps(["nc", sub, ...rest].filter(Boolean)));
  }
  if (cmd === "boot") {
    bootForeground(sub);
    return;
  }
  if (cmd === "env") {
    if (!sub) {
      console.log(currentEnv());
      return;
    }
    setEnv(sub);
    return;
  }
  if (cmd === "setup") {
    await setupInteractive();
    return;
  }
  if (cmd === "set") {
    setKey(sub, rest.join(" ").trim());
    return;
  }
  if (cmd === "status") {
    status();
    return;
  }
  if (cmd === "create" && sub === "plugin") {
    createPlugin(rest[0] ?? "my-plugin");
    return;
  }
  if (cmd === "registry" && sub === "show") {
    const local = join(root, "configs/registry.local.json");
    const def = join(root, "configs/registry.json");
    console.log(readFileSync(existsSync(local) ? local : def, "utf8"));
    return;
  }
  help();
  process.exit(1);
}

main().catch((e) => {
  console.error(e instanceof Error ? e.message : e);
  process.exit(1);
});
